site_name: MkDocs GLightbox

repo_url: https://github.com/blueswen/mkdocs-glightbox
repo_name: blueswen/mkdocs-glightbox
site_url: https://blueswen.github.io/mkdocs-glightbox/
site_dir: ../docs
edit_uri: ""

theme:
  name: material
  icon:
    logo: material/projector
  features:
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  analytics:
    provider: google
    property: G-KQTG9N2Y4N

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - meta
  - md_in_html
  - admonition

plugins:
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox

nav:
  - Home: index.md
  - Taiwan:
    - Sea: taiwan/sea.md
    - Mountain: taiwan/mountain.md
  - Caption: caption/caption.md
  - Gallery: gallery/gallery.md
  - More Flexibility:
    - Disable by image: disable/image.md
    - Disable by page: disable/page.md
    - Enable by image: disable/manual.md
