site_name: MkDocs GLightbox

repo_url: https://github.com/blueswen/mkdocs-glightbox
repo_name: blueswen/mkdocs-glightbox
site_url: https://github.com/blueswen/mkdocs-glightbox/
site_dir: ../docs

theme:
  name: material
  
  features:
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox:
      touchNavigation: true
      loop: true
      height: auto
      width: 80%

nav:
  - Home: index.md
  - Taiwan:
    - Sea: taiwan/sea.md
    - Mountain: taiwan/mountain.md
  - Gallery: gallery.md
